maintainers:
  - user:    kwatch
    name:    makoto kuwata
    email:   kwa@kuwata-lab.com
    role:    lead

releases:
  - version: 3.1.1
    date:    2006-09-29
    state:   beta
    notes: |
      * initial release

documents:
  - doc/docstyle.css
  - doc/users-guide.html
  - doc/reference.html
  - doc/pattern-catalog.html
  - doc/pattern-catalog/design.*
  - doc/img/*.png
  - README.txt
  - ChangeLog
  - LGPL
#  - COPYING
  - examples/**/*


